version: '3'

services:
  php:
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    container_name: php83
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mariadb:11.3
    container_name: mariadb11
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MARIADB_DATABASE: defaultdb
      MARIADB_ROOT_PASSWORD: mariaroot
      MARIADB_USER: mariauser
      MARIADB_PASSWORD: password

volumes:
  db_data:
